# 服务提供者eureka配置
server:
  port: 9091
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3
    username: root
    password: root
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka,http://127.0.0.1:10088/eureka
  instance:
    # 服务失效时间默认炎90秒
    lease-expiration-duration-in-seconds: 90
    # 服务续约（renew）间隔默认30秒
    lease-renewal-interval-in-seconds: 30
